// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package schedule

import (
	"github.com/google/wire"
	"monitor-service/conf"
	"monitor-service/internal/db"
)

// Injectors from wire.go:

func CreateSchedule() (*Schedule, error) {
	configuration := conf.NewConfiguration()
	database := db.NewDatabase()
	schedule := NewSchedule(configuration, database)
	return schedule, nil
}

// wire.go:

var ProviderScheduleSet = wire.NewSet(conf.NewConfiguration, db.NewDatabase, NewSchedule)
